#! /usr/bin/env php

<?php 
include "src/Pacman/Days.php";

$birthday = "1983-12-18";

$days = new \romaxa\Pacman\Days($birthday);

$total = $days->countDays();

echo "Кол-во дней - " . $total . PHP_EOL;
